---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myecho
  labels:
    app: myecho
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: myecho
  template:
    metadata:
      labels:
        app: myecho
    spec:

      containers:
        - name: myecho
          image: "myecho:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8090
          command: ["./myecho.exe"]
          args: []
          livenessProbe:
            httpGet:
              path: "/status"
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: myecho-service
spec:
  type: ClusterIP
  ports:
    - port: 8090
      protocol: TCP
      name: http
  selector:
    app: myecho
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myecho-ingress
spec:
  ingressClassName: nginx
  rules:
    - #host: hello-world.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myecho-service
                port:
                  number: 8090
